repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "23.11.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E24,W503,E704,E123,E121,E226,W504,E126,E203"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1"
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest -m "not slow"
        language: system
        types:
          - python
        pass_filenames: false
