from aoc23 import p11


def test_example_1() -> None:
    lines = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
""".strip().splitlines()
    assert (
        p11.sum_shortest_paths(
            p11.parse_input(lines),
            expansion_coefficient=2,
        )
        == 374
    )


def test_example_2() -> None:
    lines = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
""".strip().splitlines()
    assert (
        p11.sum_shortest_paths(
            p11.parse_input(lines),
            expansion_coefficient=10,
        )
        == 1030
    )
